name: CI
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup JDK
        uses: actions/setup-java@v4.1.0
        with:
          java-version: 17
          distribution: temurin
          cache: sbt
      - name: Build
        run: sbt rebuild
